apiVersion: v1
kind: ServiceAccount
metadata:
  name: xk6-test-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: xk6-config-manager
  namespace: default
rules:
- apiGroups: ["", "apps"]
  resources: ["configmaps", "pods", "deployments", "replicasets"]
  verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xk6-rbac-bind
  namespace: default
subjects:
- kind: ServiceAccount
  name: xk6-test-sa
  namespace: default
roleRef:
  kind: Role
  name: xk6-config-manager
  apiGroup: rbac.authorization.k8s.io